# Generated by Django 5.2.11 on 2026-02-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_alter_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('total_floors', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('LECTURE', 'Lecture Hall'), ('LAB', 'Computer Lab'), ('SEMINAR', 'Seminar Room'), ('TUTORIAL', 'Tutorial Room')], default='LECTURE', max_length=10)),
                ('capacity', models.IntegerField(default=60)),
                ('has_projector', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_smartboard', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='resources.block')),
            ],
            options={
                'ordering': ['block', 'room_number'],
                'unique_together': {('block', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1)),
                ('credits', models.IntegerField(default=3)),
                ('hours_per_week', models.IntegerField(default=3, help_text='Contact hours per week')),
                ('max_students', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='resources.classroom')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_courses', to='attendance.department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_courses', to='attendance.faculty')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Above Average'), ('C', 'Average'), ('F', 'Fail'), ('-', 'Not Graded')], default='-', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='resources.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_enrollments', to='attendance.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='WorkloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(default='2024-25', max_length=9)),
                ('total_courses', models.IntegerField(default=0)),
                ('total_hours_week', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('OVERLOADED', 'Overloaded'), ('UNDERLOAD', 'Underloaded')], default='NORMAL', max_length=10)),
                ('calculated_on', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_records', to='attendance.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'semester', 'academic_year')},
            },
        ),
    ]
