# Generated by Django 5.2.11 on 2026-02-22 18:16

import django.db.models.deletion
import makeup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_alter_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(help_text='e.g. Block 32 Room 101', max_length=100)),
                ('reason', models.CharField(choices=[('HOLIDAY', 'Previous Class Missed — Holiday'), ('SICK', 'Faculty Was Sick'), ('EVENT', 'College Event'), ('EXTRA', 'Extra Coverage Needed'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('remedial_code', models.CharField(default=makeup.models.generate_remedial_code, max_length=6, unique=True)),
                ('code_active', models.BooleanField(default=False)),
                ('code_activated_at', models.DateTimeField(blank=True, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_score', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions', to='attendance.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions', to='attendance.faculty')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_date', models.DateField()),
                ('suggested_time', models.TimeField()),
                ('score', models.IntegerField(default=0, help_text='0-100, higher = better')),
                ('reason', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='makeup.makeupsession')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='MakeUpAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('code_used', models.CharField(max_length=6)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_attendances', to='attendance.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='makeup.makeupsession')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
